name: Update Lambda Function

on:
  push:
    branches:
      - master

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: decrypt config
        run: ./decrypt_secret.sh
        env:
          CREDS_PASSPHRASE: ${{ secrets.CREDS_PASSPHRASE }}
      - name: install-cli
        run : |
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          ./awscli-bundle/install -b ~/bin/aws
      - name: zip-lambda
        run: zip -r deep_lens_smile_inferer.zip deep-lens-smile-inferer
      - name: upload-new-lambda
        run: |
          aws lambda update-function-code \
          --function-name arn:aws:lambda:us-east-1:880540780340:function:deeplens-smile-inferer \
          --zip-file deep_lens_smile_inferer.zip \
          --publish true \
          --dry-run true
